//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuvantuyensinhsv.v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public string Tieude { get; set; }
        public string Noidung { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public string Tabs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
