//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuvantuyensinhsv.v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatePost
    {
        public int IDBaiViet { get; set; }
        public string IDUsername { get; set; }
        public bool Like { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
