//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuvantuyensinhsv.v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruongNganh
    {
        public string MaTruong { get; set; }
        public string MaNganh { get; set; }
        public string KhoiThi { get; set; }
        public Nullable<double> Diem1 { get; set; }
        public Nullable<double> Diem2 { get; set; }
        public Nullable<double> Diem3 { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual Nganh Nganh { get; set; }
        public virtual Truong Truong { get; set; }
    }
}
